#pragma once
#include <chrono>
#include <stdexcept>
#include <string>

#include <nlohmann/json.hpp>

enum class OrderSide { Buy, Sell };
enum class OrderType { Market, Limit };

inline std::string toString(OrderSide side) { return side == OrderSide::Buy ? "buy" : "sell"; }

inline std::string toString(OrderType type) { return type == OrderType::Market ? "market" : "limit"; }

inline OrderSide orderSideFromString(const std::string& value) {
    if (value == "buy") return OrderSide::Buy;
    if (value == "sell") return OrderSide::Sell;
    throw std::runtime_error("Order: unknown side '" + value + "'");
}

inline OrderType orderTypeFromString(const std::string& value) {
    if (value == "market") return OrderType::Market;
    if (value == "limit") return OrderType::Limit;
    throw std::runtime_error("Order: unknown type '" + value + "'");
}

// A request to place one order on one venue. orderId is generated by the
// submitter (strategy/CLI) and doubles as the idempotency key: execution_service
// uses it to detect and skip a redelivered stream entry it has already acted on.
struct Order {
    std::string orderId;
    std::string strategyId;
    std::string venue;   // e.g. "BINANCE_Spot", "BYBIT_Spot" — matches IExecutionConnector::exchangeName()
    std::string symbol;  // exchange-native symbol, e.g. "BTCUSDT"
    OrderSide side = OrderSide::Buy;
    OrderType type = OrderType::Limit;
    double qty = 0.0;
    double price = 0.0;  // ignored for OrderType::Market
    std::chrono::system_clock::time_point submittedAt;
};

inline nlohmann::json toJson(const Order& order) {
    const auto submittedAtMs = std::chrono::duration_cast<std::chrono::milliseconds>(
                                    order.submittedAt.time_since_epoch())
                                    .count();
    return nlohmann::json{
        {"order_id", order.orderId},   {"strategy_id", order.strategyId},
        {"venue", order.venue},        {"symbol", order.symbol},
        {"side", toString(order.side)}, {"type", toString(order.type)},
        {"qty", order.qty},            {"price", order.price},
        {"submitted_at_ms", submittedAtMs},
    };
}

inline Order orderFromJson(const nlohmann::json& json) {
    Order order;
    order.orderId = json.at("order_id").get<std::string>();
    order.strategyId = json.value("strategy_id", "");
    order.venue = json.at("venue").get<std::string>();
    order.symbol = json.at("symbol").get<std::string>();
    order.side = orderSideFromString(json.at("side").get<std::string>());
    order.type = orderTypeFromString(json.at("type").get<std::string>());
    order.qty = json.at("qty").get<double>();
    order.price = json.value("price", 0.0);
    order.submittedAt =
        std::chrono::system_clock::time_point(std::chrono::milliseconds(json.value("submitted_at_ms", int64_t{0})));
    return order;
}
